disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - function_parameter_count
 - line_length
 - implicit_getter
 - vertical_whitespace
 - file_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
